POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmNzc0MjFlNDk0NzVkNDA1OGUyYzQ2YiIsImlhdCI6MTYwMTY1MTI1OX0.Ryg05ywrK4vOfJgPXBd4V8cQzdRzWEUl8nTrJqwcvGo

{
  "title": "blog6",
    "url": "https://medium.com/better-programming",
    "likes": 0
}
