PUT http://localhost:3003/api/blogs/5f49152295740c1144cb47e6
Content-Type: application/json

{
    "title": "new",
    "author": "multiple",
    "url": "https://medium.com/better-programming",
    "likes": 3
}
